export const GITHUB_REPO_BASE_URL = 'https://api.github.com/search/repositories';
export const PAGE_SIZE = 10;
export const DEBOUNCE_INTERVAL = 300;
export const UNKNOWN_AUTHOR = '(Unknown Author)';
export const NO_BIO_PROVIDED = '(No Bio Provided)';
export const DEFAULT_PAGING_INFO = { page: 1, query: '', totalCount: 0 };
export const DEFAULT_PAGE = 1;
export const DEFAULT_QUERY = '';
export const DEFAULT_TOTAL_COUNT = 0;
